version: '3.2'

services:
  filebeat:
    build:
      context: extensions/filebeat-compose/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./extensions/filebeat-compose/config/filebeat.yml
        target: /usr/share/filebeat/filebeat.yml
        read_only: true
      - ./logs:/var/log/apps
    networks:
      - elk
    depends_on:
      - logstash