filebeat:
  inputs:
    -
      paths:
        - /var/log/apps/*.log
      input_type: log
      multiline.pattern: '^[DIWEF]'
      multiline.negate: true
      multiline.match: after

output:
  logstash:
    hosts: ["logstash:5044"]
